BOARD_TAG = mega2560
MONITOR_PORT  = /dev/ttyACM3
ARDUINO_DIR = /usr/share/arduino
USER_LIB_PATH := ./libraries
ARDUINO_LIBS = AccelStepper/src LiquidCrystal Arduino_LCD_Menu
include /usr/share/arduino/Arduino.mk
