BOARD_TAG = mega2560
MONITOR_PORT  = /dev/ttyACM3
ARDUINO_DIR = /usr/share/arduino
USER_LIB_PATH := ../../../.
ARDUINO_LIBS = USB_Host_Shield Arduino_Camera_Control Time
include /usr/share/arduino/Arduino.mk
